import sourceData from "../../../data/placements.json";
import overrideData from "../../../data/confirmed-overrides.json";
import rawSourceMeta from "../../../data/raw-source-meta.json";

function newestTimestamp(...candidates) {
  return candidates.reduce((latest, current) => {
    if (!current || Number.isNaN(Date.parse(current))) return latest;
    if (!latest || Date.parse(current) > Date.parse(latest)) return current;
    return latest;
  }, null);
}

function normalizeAddition(addition) {
  const shortName = (addition.name || addition.slug || "NA")
    .split(/\s+/)
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
  return {
    slug: addition.slug,
    name: addition.name,
    shortName,
    companyUrl: null,
    industry: "Software engineering",
    package: { stipend: null },
    ppo: null,
    description: addition.currentStage || "Campus application submitted; awaiting next-stage details.",
    roles: addition.roles || (addition.role ? [addition.role] : []),
    requirements: [],
    eligibility: [],
    skills: [],
    deadline: null,
    applicationUrl: null,
    jdUrl: null,
    jdLinks: [],
    timeline: [],
    source: "Placement Tracker 2026 / confirmed user state",
    ...addition,
  };
}

function applyConfirmedState(sourceCompanies, overrides) {
  const companies = new Map((sourceCompanies || []).map((company) => [company.slug, company]));
  for (const override of overrides.overrides || []) {
    const existing = companies.get(override.slug) || { slug: override.slug };
    const merged = { ...existing, ...override };
    if (override.applicationStatus === "Not Applicable" || override.applicationStatus === "Not Applied") {
      merged.deadline = null;
      merged.timeline = [];
    }
    companies.set(override.slug, merged);
  }
  for (const addition of overrides.additions || []) {
    const existing = companies.get(addition.slug);
    companies.set(addition.slug, existing ? { ...existing, ...addition } : normalizeAddition(addition));
  }
  const exclusions = new Set((overrides.exclusions || []).map((name) => name.toLowerCase()));
  return Array.from(companies.values()).filter((company) => {
    const name = (company.name || "").toLowerCase();
    const slug = (company.slug || "").toLowerCase();
    return !Array.from(exclusions).some((excluded) => name.includes(excluded) || slug.includes(excluded));
  });
}

function applyRuntimeCorrections(sourceCompanies) {
  const companies = [...sourceCompanies];
  const upsert = (addition) => {
    const i = companies.findIndex((c) => c.slug === addition.slug);
    if (i >= 0) companies[i] = { ...companies[i], ...addition };
    else companies.push(normalizeAddition(addition));
  };

  upsert({ slug: "idfc-first-bank", applicationStatus: "Not Selected", currentStage: "OA completed on 10-Aug-2026. IDFC FIRST Bank sent a direct update on 22-Aug-2026 confirming they will not move forward with Puneet's Application Engineer application.", nextAction: "No further action for this application unless a new IDFC role opens.", deadline: null, timeline: [{ stage: "OA completed", date: "10 August 2026" }, { stage: "Application closed by IDFC FIRST Bank", date: "22 August 2026" }] });
  upsert({ slug: "evertz-india", currentStage: "Evertz online assessment was held on 19-Aug-2026. The official 20-Aug absentee blacklist did not include Puneet; personal result/next-round status is still pending.", nextAction: "Wait for Evertz result / next-round communication." });
  upsert({ slug: "relyntis-software", applicationStatus: "Need Info", currentStage: "Registration deadline passed on 19-Aug-2026 at 5:00 PM. No connected-source evidence confirms whether Puneet submitted the RELYNTIS form.", nextAction: "No active deadline; treat personal application status as unconfirmed unless newer evidence appears." });
  upsert({ slug: "eurofins", applicationStatus: "Not Shortlisted", currentStage: "Official Eurofins final shortlist for the 9–10 Sep process was published on 21-Aug-2026; Puneet is not on it.", nextAction: "No Eurofins action unless a corrected/additional shortlist is published.", timeline: [{ stage: "Final shortlist published", date: "21 August 2026; Puneet not listed" }] });
  upsert({ slug: "sartorius-india", package: { stipend: "₹20,000 per month" }, applicationStatus: "Not Selected", currentStage: "Sartorius Stedim India published the final LCM & Quality Team internship result on 21-Aug-2026; Puneet is not among the final selects.", nextAction: "No Sartorius action unless a newer official correction/additional selection appears.", timeline: [{ stage: "Final selection published", date: "21 August 2026; Puneet not selected" }] });
  upsert({ slug: "amd-india", name: "AMD India Pvt Ltd", role: "Co-Op / Internship (with PPO) — Software/Hardware domain allocation", industry: "Semiconductors / Software / Hardware / Systems", package: { stipend: "₹40,000 per month for B.Tech" }, ppo: "BE FTE Year-1 earning potential ₹19.45 LPA", applicationStatus: "Not Applied", currentStage: "AMD registration deadline passed on 21-Aug-2026 at 7:00 AM without a completed registration/resume upload. A newer 27-Aug RVITM update says AMD considered only RVCE students this time.", nextAction: "No current action unless RVITM/AMD opens a separate RVITM opportunity.", deadline: null, timeline: [], source: "RVITM Placement WhatsApp archive plus deadline verification" });
  upsert({ slug: "dover-india", name: "Dover India", role: "Associate Software Engineer", industry: "Software Engineering / Industrial Technology", package: { stipend: "₹25,000 per month" }, ppo: "₹12 LPA FTE + ₹2 lakh joining bonus", applicationStatus: "Not Applied", currentStage: "Dover registration deadline passed on 22-Aug-2026 at 9:00 AM with Puneet's Gender field still blank; resume entry was present but registration remained incomplete.", nextAction: "No current action unless RVITM/Dover reopens registration or accepts a correction.", deadline: null, timeline: [], source: "Official Dover registration sheet" });
  upsert({ slug: "arctic-wolf-networks", name: "Arctic Wolf Networks", role: "Security / Software Intern (Internship + PPO)", industry: "Cybersecurity / Software Engineering", package: { stipend: "₹60,000 per month" }, ppo: "₹22 LPA last-year CTC reference", applicationStatus: "Not Shortlisted", currentStage: "RVITM placement leadership confirmed on 21-Aug-2026 that no student from RVITM was shortlisted by Arctic Wolf.", nextAction: "No action unless a revised shortlist/reopening appears.", timeline: [{ stage: "RVITM no-shortlist confirmation", date: "21 August 2026" }], source: "RVITM Placement WhatsApp dated 21-Aug-2026" });
  upsert({ slug: "juspay", name: "Juspay Technologies", role: "Software Development Engineer (SDE)", industry: "Payments Technology / Backend / Distributed Systems / Infrastructure", package: { stipend: "₹40,000 per month" }, ppo: "₹27 LPA CTC", applicationStatus: "Applied", appliedDate: "2026-08-23", currentStage: "Juspay OA session is active on 28-Aug-2026 at RVITM. The official room-allotment sheet places Puneet Dixit in room L517. The first WeCP test link was exhausted; RVITM issued a replacement test link at 10:40 AM and the assessment password at 10:45 AM.", nextAction: "Remain/report in room L517 and use the replacement assessment link only when the Placement Team/Lab Incharge explicitly instructs students to start. After the OA, monitor for result, hackathon and technical-round communication.", deadline: null, timeline: [{ stage: "Registration confirmed", date: "23 August 2026" }, { stage: "Virtual Pre-Placement Talk", date: "25 August 2026, 3:45 PM IST" }, { stage: "Online Assessment", date: "28 August 2026 at RVITM, room L517; exact start/end per placement-team instruction" }], source: "Official RVITM Placement Gmail and official Juspay room-allotment sheet dated 28-Aug-2026", notes: "RVITM instructed students not to start/access the assessment until told to do so. Replacement link and password were issued after the original link was exhausted." });
  upsert({ slug: "qnance-technologies", name: "Qnance Technologies LLP", role: "Software Developer Intern", industry: "Software Engineering / Product Development", package: { stipend: "₹70,000 per month" }, ppo: "> ₹12 LPA FTE, performance-based conversion", requirements: ["BE CS & EC cluster", "8.0 CGPA & above", "No current backlogs"], applicationUrl: "https://docs.google.com/spreadsheets/d/1YDv76kXupmefO6V77VGUER_B06uYK1oY0pe8PRUYZAg/edit?usp=sharing", applicationStatus: "Applied", appliedDate: "2026-08-25", currentStage: "Official Qnance registration sheet confirms Puneet / 1RF23CS119 with Gender and resume populated.", nextAction: "Prepare for the Qnance PPT + Online Assessment on 4-Sep-2026 and monitor for exact time/venue.", deadline: null, timeline: [{ stage: "Registration completed", date: "25 August 2026" }, { stage: "PPT + Online Assessment", date: "4 September 2026; time TBD" }, { stage: "Interviews", date: "5–7 September 2026; personal slot TBD" }], source: "RVITM Placement WhatsApp plus official registration sheet" });
  upsert({ slug: "kinaxis", name: "Kinaxis", role: "Associate Consultant", industry: "Supply Chain Software / Enterprise SaaS / Consulting", package: { stipend: "₹35,000 per month" }, ppo: "₹8 LPA base FTE; 6-month internship + FTE conversion LOI", applicationStatus: "Not Applied", currentStage: "Kinaxis registration closed before 9:00 AM on 25-Aug-2026. Final recheck found no Puneet / 1RF23CS119 registration row and no required Puneet-named resume upload. A newer 27-Aug shortlist names four students and does not include Puneet.", nextAction: "No active Kinaxis action unless RVITM/Kinaxis explicitly publishes a corrected/additional shortlist involving Puneet.", deadline: null, timeline: [], source: "Official Kinaxis registration sheet plus RVITM Placement WhatsApp" });
  upsert({ slug: "cargill-dtd", name: "Cargill", role: "DT&D Internship Program – Software Engineer pathway", applicationStatus: "Applied", currentStage: "Both mandatory registrations are complete. The Cargill PPT was held on 26-Aug-2026 at RVITM Auditorium; a raw placement update said it started at 11:00 AM. No Cargill rejection email is present in connected Gmail.", nextAction: "Prepare for the 31-Aug 2:00 PM online test if shortlisted and monitor for any pre-test instructions. Only refill Cargill forms if an actual rejection message is received.", timeline: [{ stage: "Both registrations completed", date: "18 August 2026" }, { stage: "Pre-Placement Talk", date: "26 August 2026 at RVITM Auditorium" }, { stage: "Online Test", date: "31 August 2026, 2:00 PM" }, { stage: "Interviews", date: "11 September 2026, 10:00 AM; conditional on progression" }], source: "Official RVITM/Cargill evidence plus 26-Aug WhatsApp update" });
  upsert({ slug: "outbox", name: "OutBox", role: "Software Development Engineer – Intern", industry: "Full Stack Development / Software Engineering", package: { stipend: "₹30,000–₹40,000 per month" }, ppo: "₹10–12 LPA", applicationStatus: "Applied", appliedDate: "2026-08-25", currentStage: "Official RVITM registered-student list published 27-Aug-2026 confirms Puneet Dixit / 1RF23CS119 registered for OutBox. Mandatory SDE assignment must be submitted before Saturday, 29-Aug-2026; the official reminder gives no exact clock cutoff.", nextAction: "Complete and submit the OutBox SDE assignment before 29-Aug-2026, ensure the work is your own, and verify the submission is shared/accessibly permissioned for the OutBox team.", deadline: "Before Saturday, 29 August 2026; exact clock cutoff not stated", timeline: [{ stage: "Registration confirmed", date: "27 August 2026" }, { stage: "Mandatory SDE assignment deadline", date: "Before Saturday, 29 August 2026; exact cutoff time not stated" }], applicationUrl: "https://sumptuous-word-80f.notion.site/Software-Development-Intern-Assignment-2bc1596f45e88080995cec1180a2bc60", source: "Official RVITM registered-student list + assignment reminder dated 27-Aug-2026" });
  upsert({ slug: "nhai-internship-program", name: "NHAI (National Highways Authority of India)", role: "Winter Internship Programme 2026-27 / Term Internship Programme 2027", industry: "Government Infrastructure / Highway Projects / Technology", package: { stipend: "₹20,000 per month" }, applicationStatus: "Considering", currentStage: "Official AICTE notice forwarded by RVITM; NHAI student application deadline is 20-Oct-2026.", nextAction: "Verify institute eligibility and submit the NHAI portal application before 20-Oct-2026.", deadline: "20 October 2026; exact clock cutoff not stated", timeline: [{ stage: "Student application deadline", date: "20 October 2026; time TBD" }, { stage: "Institute verification/recommendation deadline", date: "10 November 2026" }], applicationUrl: "https://internshipsatnhai.digitalindiacorporation.in/" });
  upsert({ slug: "walmart-global-tech", name: "Walmart Global Tech", role: "Full-Time + Internship — 2027 Campus Drive", industry: "Software Engineering / Global Technology / Enterprise Systems", ppo: "BE total compensation ₹26.09 LPA", applicationStatus: "Applied", appliedDate: "2026-08-26", currentStage: "Official Walmart registration sheet confirms Puneet / 1RF23CS119 with Gender = Male and Resume Link populated. Newer RVITM scheduling on 26-Aug postpones Walmart again to Friday, 28-Aug-2026. No exact OA time/venue update is confirmed yet.", nextAction: "Prepare for the 28-Aug Walmart OA and monitor RVITM communication for the exact time/venue and reporting instructions.", deadline: null, timeline: [{ stage: "Registration completed", date: "26 August 2026" }, { stage: "Online Assessment", date: "Friday, 28 August 2026; exact time/venue TBD" }], source: "RVITM Placement WhatsApp plus official Walmart registration sheet", notes: "The 26-Aug postponement supersedes the earlier 27-Aug OA date. The previously listed 1-Sep interview date should be treated as provisional until reconfirmed after the postponement." });
  upsert({ slug: "qualcomm-hw-2027", name: "Qualcomm", role: "Full-Time HW — 2027 Campus Drive", industry: "Semiconductors / Hardware Engineering / Embedded Systems", applicationStatus: "Applied", appliedDate: "2026-08-26", currentStage: "Direct HirePro email on 27-Aug-2026 confirms Qualcomm Online Test credentials were issued to Puneet for the proctored remote OA scheduled at 3:00 PM. OA participation/completion is not independently verified after the test window.", nextAction: "Monitor Gmail/placement communication for the Qualcomm OA result or next-stage shortlist. Do not mark the OA completed unless direct evidence or user confirmation appears.", deadline: null, timeline: [{ stage: "Registered candidate / test credentials issued", date: "27 August 2026" }, { stage: "Remote proctored Online Assessment", date: "27 August 2026, 3:00 PM; participation unverified" }], source: "Direct HirePro Qualcomm Online Test Credentials email + official RVCE/RVITM updates", notes: "Receipt of direct Online Test Credentials is stronger evidence of personal OA eligibility than the earlier blank Resume Link field concern." });
  upsert({ slug: "baker-hughes", name: "Baker Hughes", role: "Digital Technology Intern", industry: "Digital Technology / Software / Engineering", package: { stipend: "₹50,000 per month" }, ppo: "₹12 LPA CTC/PBC", requirements: ["Minimum CGPA 7.5/10", "No current backlogs"], applicationUrl: "https://docs.google.com/spreadsheets/d/14Wu04_8bztxZWVofUWrGDqTTA75C_D4_8JryWayMNt8/edit?usp=sharing", applicationStatus: "Applied", appliedDate: "2026-08-28", currentStage: "Official Baker Hughes registration sheet confirms Puneet / 1RF23CS119 with Gender = Male and the Baker Hughes resume populated before the 28-Aug-2026 9:00 AM deadline.", nextAction: "Prepare for the full-day Baker Hughes campus drive on 2-Sep-2026 and monitor for exact reporting time, venue and round instructions.", deadline: null, timeline: [{ stage: "Registration completed", date: "28 August 2026" }, { stage: "Campus placement drive", date: "2 September 2026; full day" }], source: "Official Baker Hughes registration sheet plus RVITM Placement WhatsApp" });
  upsert({ slug: "cloudera", name: "Cloudera", role: "Software Engineering Intern", industry: "Cloud Data / Distributed Systems / Software Engineering", package: { stipend: "₹45,000 per month" }, ppo: "~₹20 LPA full-time CTC (₹18 LPA base), conversion based on internship performance", requirements: ["BE CS Cluster", "7.5 CGPA & above", "No active backlogs"], applicationUrl: "https://docs.google.com/spreadsheets/d/1BUeut0Qvp0AhBnqhv0yIPDd-pNye_DuGIaprU6kfr-U/edit?usp=sharing", applicationStatus: "Applied", appliedDate: "2026-08-28", currentStage: "Fresh RVITM placement update on 27-Aug announced Cloudera. Official registration sheet row 89 confirms Puneet / 1RF23CS119 with Gender = Male and Resume Link populated, so registration is complete before the 28-Aug 8:00 AM deadline.", nextAction: "Prepare for the Cloudera on-campus drive at RVCE on 2–3 Sep 2026 and monitor for exact daily reporting time, venue and round sequence.", deadline: null, timeline: [{ stage: "Registration completed", date: "28 August 2026" }, { stage: "On-campus drive at RVCE", date: "2–3 September 2026; exact daily time TBD" }, { stage: "Internship", date: "January–June 2027" }], source: "RVITM Placement WhatsApp dated 27-Aug-2026 plus official Cloudera registration sheet" });
  upsert({ slug: "gyansys", name: "GyanSys", role: "Internship + PPO", industry: "Software / Enterprise Technology / Consulting", package: { stipend: "₹25,000 per month" }, ppo: "₹8 LPA full-time CTC including 10% variable pay", requirements: ["BE CS & EC clusters", "85% throughout 10th, 12th/Diploma and Graduation"], applicationUrl: "https://docs.google.com/spreadsheets/d/1D6xcGgauAuS4aHP416F4VnrReznI6642z2jooK-lsbE/edit?usp=sharing", applicationStatus: "Not Eligible", currentStage: "RVITM announced GyanSys on 27-Aug-2026 with registration by 28-Aug-2026 at 8:00 AM. Puneet does not meet the published 85%-throughout cutoff because his official 12th score is 83.", nextAction: "No action unless RVITM/GyanSys revises the eligibility cutoff or publishes an exception.", deadline: null, timeline: [], source: "RVITM Placement WhatsApp dated 27-Aug-2026 plus official academic score evidence", notes: "Raw notice: on-campus at RVCE, drive date TBD, internship starts mid-Jan 2027, Bengaluru/Hyderabad/Pune, full-time confirmations may be extended starting from the third month based on performance." });
  upsert({ slug: "coupa", name: "Coupa", role: "Software Engineer – Intern (Internship followed by PBC to FTE)", industry: "Enterprise SaaS / Software Engineering / Spend Management", package: { stipend: "₹65,000 per month" }, ppo: "₹20 LPA CTC", requirements: ["B.E. CSE, ISE, ECE, EEE, DS, CY, ETCE, AIML", "7.0+ CGPA", "No current backlogs"], applicationUrl: "https://docs.google.com/spreadsheets/d/1K3r1qe8S0OplabpLK6bfw9D5C0IiW8FtE9c3c9WaBJo/edit?usp=sharing", applicationStatus: "Not Applied", currentStage: "RVITM announced Coupa on 26-Aug-2026 with a same-day 6:00 PM deadline. Final post-deadline recheck finds neither Puneet nor USN 1RF23CS119 in the official Coupa registration sheet. A 27-Aug raw update gives an 8:45 AM 28-Aug interview venue for active candidates, but it is non-actionable for Puneet.", nextAction: "No active Coupa action unless RVITM/Coupa reopens registration or publishes a correction/additional list.", deadline: null, timeline: [], source: "RVITM Placement WhatsApp dated 26–27 Aug plus official Coupa sheet", notes: "Drive was virtual; later interview logistics do not apply because no completed registration was found." });
  upsert({ slug: "tekoraai", name: "TekoraAI", role: "Software / AI Internship Programme", industry: "AI / Software Development / Full Stack", package: { stipend: "Unpaid" }, ppo: null, applicationStatus: "Need Info", currentStage: "Official RVITM CSE forward received 27-Aug-2026. TekoraAI asks RVITM to nominate/select 4 candidates for free internships; no nomination form, college deadline, or personal nomination is published yet.", nextAction: "Monitor RVITM for the 4-candidate nomination/selection process and deadline. Do not pay an internship fee unless RVITM explicitly recommends participation and the terms are independently acceptable.", deadline: null, timeline: [{ stage: "RVITM nomination / task-based selection", date: "TBD" }], requirements: ["RVITM forwarding note says CSE students only", "Company email lists CS, AI and Data Science"], skills: ["Python", "Java", "JavaScript", "SQL", "React", "Node.js", "AI/ML basics", "Git/GitHub", "Docker", "Cloud/DevOps basics"], applicationUrl: "https://tekora.ai/", source: "Official RVITM CSE forward / direct TekoraAI email dated 26-Aug-2026", notes: "Direct company email says 4 free internship seats, no stipend, no FTE hiring, task-based selection, Bengaluru Manyata Tech Park and 1/2/3/6-month options. Other participants may be charged internship fees. The attached marketing brochure separately claims pathways to full-time careers and an 80%+ conversion rate; because this conflicts with the direct email, the tracker preserves the direct email's 'No FTE hiring' statement as authoritative for this RVITM opportunity." });

  return companies;
}

function buildAnnouncements(companies) {
  const bySlug = new Map(companies.map((company) => [company.slug, company]));
  const announcements = [];
  if (bySlug.get("baker-hughes")?.applicationStatus === "Applying") announcements.push({ id: "baker-hughes-deadline-2026-08-28", title: "Baker Hughes registration due 9:00 AM tomorrow", message: "Baker Hughes Digital Technology Intern: Puneet's row exists, but Gender and Resume Link are blank. Complete both before 28-Aug 9:00 AM. Stipend ₹50,000/month; CTC/PBC ₹12 LPA; drive 2-Sep full day.", date: "2026-08-27", type: "warning" });
  if (bySlug.get("outbox")?.applicationStatus === "Applied") announcements.push({ id: "outbox-assignment-2026-08-29", title: "OutBox registration confirmed — assignment due before 29 Aug", message: "RVITM's official registered-student list includes Puneet. The official reminder says the assignment must be completed and submitted before Saturday 29-Aug; exact clock cutoff is not stated.", date: "2026-08-27", type: "warning" });
  if (bySlug.get("qualcomm-hw-2027")?.applicationStatus === "Applied") announcements.push({ id: "qualcomm-credentials-2026-08-27", title: "Qualcomm OA credentials received", message: "HirePro sent Puneet direct credentials for the 27-Aug 3:00 PM remote proctored OA. Participation/result is not yet independently verified; monitor for the next-stage update.", date: "2026-08-27", type: "info" });
  if (bySlug.get("walmart-global-tech")?.applicationStatus === "Applied") announcements.push({ id: "walmart-postponed-2026-08-28", title: "Walmart OA on Friday", message: "Walmart Global Tech registration is complete and the OA is scheduled for Friday, 28-Aug. Exact time/venue are TBD.", date: "2026-08-28", type: "warning" });
  if (bySlug.get("juspay")?.applicationStatus === "Applied") announcements.push({ id: "juspay-oa-2026-08-28", title: "Juspay OA active today — room L517", message: "Official room allocation places Puneet in L517. RVITM issued a replacement assessment link/password after the original link was exhausted. Do not start until the Placement Team/Lab Incharge instructs you to do so.", date: "2026-08-28", type: "warning" });
  return [...announcements, ...(sourceData.announcements || []).filter((a) => !announcements.some((x) => x.id === a.id))];
}

export async function GET() {
  const companies = applyRuntimeCorrections(applyConfirmedState(sourceData.companies || [], overrideData));
  const meta = overrideData.meta || {};
  const lastUpdated = newestTimestamp(sourceData.meta?.lastUpdated, meta.lastUpdated, rawSourceMeta.lastUpdated, rawSourceMeta.rawSourceLatestCommitAt);
  return Response.json({
    ...sourceData,
    meta: {
      ...sourceData.meta,
      lastUpdated: lastUpdated || sourceData.meta?.lastUpdated,
      rawDataThrough: rawSourceMeta.rawDataThrough || meta.rawDataThrough || sourceData.meta?.rawDataThrough,
      rawSourceLatestCommit: rawSourceMeta.rawSourceLatestCommit || meta.rawSourceLatestCommit,
      rawSourceLatestCommitAt: rawSourceMeta.rawSourceLatestCommitAt || meta.rawSourceLatestCommitAt,
      rawSourceFreshness: rawSourceMeta.rawSourceFreshness,
      notice: "Placement records combine the primary tracker with authoritative overrides and newer official updates. Baker Hughes registration is complete and the full-day drive is 2-Sep. Cloudera is Applied with an on-campus RVCE drive on 2–3 Sep, ₹45,000/month stipend and ~₹20 LPA full-time CTC. OutBox registration is confirmed and its assignment must be submitted before Saturday 29-Aug; exact clock cutoff is not stated. Juspay is Applied and its 28-Aug OA session is active at RVITM; Puneet is allotted room L517, and RVITM issued a replacement test link/password after the first link was exhausted. Students must not start until instructed. Qualcomm sent Puneet direct OA credentials for the 27-Aug 3:00 PM remote assessment; participation/result remains unverified. GyanSys is Not Eligible under the published 85%-throughout cutoff. Walmart is Applied with its 28-Aug OA exact time/venue still TBD. Cargill is Applied with the 31-Aug 2:00 PM test next if shortlisted. Qnance is Applied. TekoraAI is Need Info. IDFC is Not Selected; InMobi is Not Applicable; Sama is Not Applied; ShareChat/Eurofins are Not Shortlisted; Sartorius is Not Selected; AMD/Dover/Kinaxis/Coupa are Not Applied. Google and Flipkart remain excluded unless a fresh official notice appears.",
    },
    announcements: buildAnnouncements(companies),
    companies,
  }, { headers: { "Cache-Control": "no-store" } });
}